framework:
    default_locale: '%locale%'
    translator:
        enabled: false # pour désactiver la traduction
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
